name = "CozyGrove"
author = "SugoiDogo"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a1b93de34268b66ed28e5823c9ab66cc59311e545480baf0b88702b42342af3"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
