name = "CozyGrove"
author = "SugoiDogo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d116701a4611dc491c3a056665b7b5baf92e71c8cc5600373b5e94120b21a46"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
