name = "CozyGrove"
author = "SugoiDogo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de4a20fccce74d52513b97de2091eca26b54782ccf0eb8bef3a6d9ac3a024c7d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
