name: Build and release on version bump

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release-notes:
    name: Publish release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export pack variables
        working-directory: ./packwiz
        run: for var in $(grep = pack.toml | tr -d ' "'); do echo $var; done >> $GITHUB_ENV
      - name: Generate Release Notes
        id: create-release-notes
        uses: johnyherangi/create-release-notes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          format: "- {{subject}}"
      - name: Create Release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: ${{ steps.create-release-notes.outputs.release-notes }}

  publish-pages:
    name: Publish update to Github Pages
    needs: release-notes
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Download Packwiz
        working-directory: ./packwiz
        run: curl -L https://github.com/sugoidogo/packwiz/releases/latest/download/packwiz_linux_amd64.tar.gz | tar -xzvf - packwiz
      - name: Refresh Hashes
        working-directory: ./packwiz
        run: ./packwiz refresh
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release-modrinth:
    name: Publish Modrinth pack to Github Releases
    needs: release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Export pack variables
        working-directory: ./packwiz
        run: for var in $(grep = pack.toml | tr -d ' "'); do echo $var; done >> $GITHUB_ENV
      - name: Download Packwiz
        working-directory: ./packwiz
        run: curl -L https://github.com/sugoidogo/packwiz/releases/latest/download/packwiz_linux_amd64.tar.gz | tar -xzvf - packwiz
      - name: Build Modrinth Pack
        working-directory: ./packwiz
        run: |
          ./packwiz modrinth export
          mv ${{ env.name }}*.mrpack ../${{ env.name }}.mrpack
      - name: Publish Modrinth pack
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.name }}.mrpack
          overwrite: true
          tag: ${{ env.version	}}

  release-curseforge:
    name: Publish Curseforge pack to Github Releases
    needs: release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Export pack variables
        working-directory: ./packwiz
        run: for var in $(grep = pack.toml | tr -d ' "'); do echo $var; done >> $GITHUB_ENV
      - name: Download Packwiz
        working-directory: ./packwiz
        run: curl -L https://github.com/sugoidogo/packwiz/releases/latest/download/packwiz_linux_amd64.tar.gz | tar -xzvf - packwiz
      - name: Build Curseforge Pack
        working-directory: ./packwiz
        run: |
          ./packwiz curseforge detect
          ./packwiz curseforge export
          mv ${{ env.name }}*.zip ../${{ env.name }}-curseforge.zip
      - name: Publush Curseforge pack
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.name }}-curseforge.zip
          overwrite: true
          tag: ${{ env.version	}}

  release-prism:
    name: Publish Prism pack to Github Releases
    needs: release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Export pack variables
        working-directory: ./packwiz
        run: for var in $(grep = pack.toml | tr -d ' "'); do echo $var; done >> $GITHUB_ENV
      - name: Build Prism pack
        run: |
          mv packwiz prism/minecraft
          cd prism/minecraft
          wget https://github.com/packwiz/packwiz-installer-bootstrap/releases/latest/download/packwiz-installer-bootstrap.jar
          cd ..
          zip -r ../${{ env.name }}-prism.zip *
      - name: Release Prism pack
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.name }}-prism.zip
          overwrite: true
          tag: ${{ env.version	}}